In [114]:
import pandas as pd

In [115]:
homicidios = pd.read_excel('FortalezaHomicidios2012.xlsx', index_col=0)
homicidios = homicidios.drop(homicidios.index[119])
homicidios.describe()

,2012-01-01 00:00:00,2012-02-01 00:00:00,2012-03-01 00:00:00,2012-04-01 00:00:00,2012-05-01 00:00:00,2012-06-01 00:00:00,2012-07-01 00:00:00,2012-08-01 00:00:00,2012-09-01 00:00:00,2012-10-01 00:00:00,2012-11-01 00:00:00,2012-12-01 00:00:00
count,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,1.369748,0.890756,0.983193,0.983193,1.184874,1.008403,1.210084,1.016807,1.327731,1.252101,1.142857,1.243697
std,1.630564,1.430834,1.365329,1.396019,1.620663,1.669750,1.671668,1.295253,1.756871,1.742872,1.379546,2.016737
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000
75%,2.500000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,6.000000,10.000000,6.000000,7.000000,8.000000,9.000000,9.000000,6.000000,9.000000,8.000000,7.000000,9.000000

In [116]:
homicidios

,2012-01-01 00:00:00,2012-02-01 00:00:00,2012-03-01 00:00:00,2012-04-01 00:00:00,2012-05-01 00:00:00,2012-06-01 00:00:00,2012-07-01 00:00:00,2012-08-01 00:00:00,2012-09-01 00:00:00,2012-10-01 00:00:00,2012-11-01 00:00:00,2012-12-01 00:00:00
Bairro,,,,,,,,,,,,
AEROLANDIA,3,0,1,1,0,2,3,1,1,2,2,1
AEROPORTO,0,0,1,1,0,0,0,0,0,0,0,0
JOSE DE ALENCAR,4,1,1,1,2,0,1,1,2,4,0,3
ALDEOTA,1,0,0,0,0,1,0,0,0,0,0,6
ALTO DA BALANCA,1,1,1,2,2,1,0,1,0,0,0,1
ALVARO WEYNE,4,0,2,2,4,0,2,1,1,4,1,0
AMADEU FURTADO,0,0,0,0,0,0,0,0,0,0,0,0
ANCURI,3,4,4,0,1,0,0,1,2,0,2,1
ANTONIO BEZERRA,2,3,2,0,1,0,3,0,2,1,1,1
AUTRAN NUNES,3,0,0,1,1,2,2,0,4,3,2,0
DE LOURDES,0,0,0,0,0,0,0,0,0,0,0,0
BARRA DO CEARA,5,10,5,7,5,6,8,3,9,5,2,5
BARROSO,5,1,4,3,1,3,4,2,6,7,5,4
BELA VISTA,0,0,0,1,0,0,2,1,1,5,2,5
BENFICA,0,0,0,0,0,0,0,0,0,2,0,0
BOM FUTURO,0,0,0,0,0,0,0,0,0,0,0,0
BOM JARDIM,4,5,2,1,7,2,9,2,0,5,7,9
BONSUCESSO,3,2,0,2,4,1,2,1,5,1,0,4
CAIS DO PORTO,5,2,1,1,0,2,3,1,0,0,2,2
CAJAZEIRAS,1,1,2,0,1,0,1,1,1,0,1,2
CAMBEBA,0,0,0,0,1,0,0,0,0,2,1,0
CANINDEZINHO,2,1,2,1,2,0,2,4,2,2,3,2
CARLITO PAMPLONA,4,0,2,0,0,2,0,4,0,2,1,2
CASTELAO,1,0,0,0,0,2,2,1,0,1,0,0
CENTRO,1,1,2,2,4,0,1,1,5,3,4,6
CIDADE 2000,1,0,1,0,0,0,1,2,0,0,0,0
CIDADE DOS FUNCIONARIOS,1,0,1,2,1,1,0,2,0,1,0,0
COACU,0,0,0,0,0,0,0,0,0,0,0,0
COCO,1,0,0,0,0,0,0,0,0,0,0,0
CONJUNTO CEARA I,1,0,0,0,1,0,1,1,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
PARQUE SAO JOSE,1,1,0,0,0,2,1,1,5,1,2,3
PARQUELANDIA,1,0,0,2,0,0,0,1,0,2,0,0
PARREAO,0,0,0,0,0,0,0,0,0,0,0,0
PASSARE,3,1,3,1,3,1,2,4,4,3,2,8
PAUPINA,2,3,0,0,3,0,0,1,2,1,0,0
PEDRAS,0,1,0,0,0,0,0,0,0,0,0,0
PICI,1,2,1,3,3,1,3,3,0,2,3,1
PIRAMBU,2,2,3,3,6,6,3,2,2,3,4,2
PLANALTO AYRTON SENNA,2,4,2,1,8,2,1,1,5,1,2,1
PRAIA DE IRACEMA,1,1,0,2,1,4,1,0,0,1,0,0
PRAIA DO FUTURO I,0,0,0,2,2,2,1,2,2,0,1,0
PRAIA DO FUTURO II,0,0,0,2,2,2,1,2,1,1,1,0
PREFEITO JOSE VALTER,3,2,1,3,1,2,3,0,0,6,2,2
PRESIDENTE KENNEDY,0,0,0,0,0,0,0,1,0,0,0,1
QUINTINO CUNHA,6,3,3,1,2,3,4,1,5,4,3,1
RODOLFO TEOFILO,0,0,0,0,0,1,2,0,0,0,1,0
SABIAGUABA,1,1,0,0,0,1,0,0,2,0,1,3
SALINAS,0,0,0,0,0,0,0,0,0,0,0,0
SAO BENTO,0,0,0,0,0,0,0,0,0,0,0,0
SAO GERARDO,0,0,0,0,1,0,0,1,1,0,0,0
SAO JOAO DO TAUAPE,1,2,0,3,4,2,1,2,3,3,2,1
SAPIRANGA COITE,0,0,2,0,0,0,3,0,1,2,2,3
SERRINHA,2,2,0,4,3,0,2,2,0,1,3,2
SIQUEIRA,3,2,2,1,4,1,4,3,6,2,2,0
VARJOTA,0,0,0,0,1,0,0,0,1,0,0,0
VICENTE PINZON,4,4,3,3,4,2,2,2,6,0,2,2
MANOEL SATIRO,4,0,0,0,0,0,0,2,1,2,0,0
VILA PERY,1,0,1,0,0,0,2,0,1,0,1,0
VILA UNIAO,0,0,1,1,0,1,0,2,4,0,1,0
VILA VELHA,4,3,3,4,3,0,2,2,2,2,1,5

In [117]:
roubos = pd.read_excel('FortalezaRouboVeiculos2012.xlsx', index_col=0)
roubos = roubos.drop(roubos.index[119])
roubos.describe()

,2012-01-01 00:00:00,2012-02-01 00:00:00,2012-03-01 00:00:00,2012-04-01 00:00:00,2012-05-01 00:00:00,2012-06-01 00:00:00,2012-07-01 00:00:00,2012-08-01 00:00:00,2012-09-01 00:00:00,2012-10-01 00:00:00,2012-11-01 00:00:00,2012-12-01 00:00:00
count,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,3.932773,1.815126,2.487395,2.512605,2.764706,2.932773,3.067227,3.462185,3.521008,4.109244,4.067227,3.781513
std,3.984570,2.139089,2.851897,3.143100,3.451126,3.490255,3.819511,4.070959,4.133060,4.524491,4.518758,4.329950
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
50%,3.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,2.000000
75%,6.000000,3.000000,4.000000,3.000000,4.000000,4.000000,4.000000,5.000000,5.000000,7.000000,6.000000,6.000000
max,19.000000,9.000000,14.000000,15.000000,17.000000,22.000000,16.000000,18.000000,19.000000,24.000000,22.000000,24.000000

In [118]:
roubos

,2012-01-01 00:00:00,2012-02-01 00:00:00,2012-03-01 00:00:00,2012-04-01 00:00:00,2012-05-01 00:00:00,2012-06-01 00:00:00,2012-07-01 00:00:00,2012-08-01 00:00:00,2012-09-01 00:00:00,2012-10-01 00:00:00,2012-11-01 00:00:00,2012-12-01 00:00:00
Bairro,,,,,,,,,,,,
AEROLANDIA,4,2,1,1,1,0,2,6,3,3,6,5
AEROPORTO,0,0,0,0,0,0,0,0,1,0,0,0
JOSE DE ALENCAR,0,0,0,0,1,1,1,0,0,0,1,0
ALDEOTA,19,8,13,11,10,7,15,9,19,9,13,19
ALTO DA BALANCA,0,0,0,0,0,1,0,0,1,1,1,0
ALVARO WEYNE,3,0,3,4,2,3,1,5,6,9,3,4
AMADEU FURTADO,0,0,0,0,0,3,0,2,1,0,1,2
ANCURI,0,1,1,1,1,0,1,1,0,1,1,2
ANTONIO BEZERRA,14,8,13,8,9,10,7,13,15,9,3,9
AUTRAN NUNES,2,0,0,2,0,4,2,5,2,3,0,4
DE LOURDES,0,0,0,0,0,0,0,0,0,0,0,0
BARRA DO CEARA,9,1,3,9,5,7,9,9,7,2,3,6
BARROSO,6,4,4,1,1,5,2,3,1,3,4,2
BELA VISTA,11,2,2,2,4,1,4,1,2,3,6,1
BENFICA,6,3,4,4,3,2,4,5,6,0,5,11
BOM FUTURO,0,1,0,0,0,0,0,0,0,0,0,0
BOM JARDIM,12,1,7,2,8,10,3,4,15,9,9,7
BONSUCESSO,7,4,4,4,14,5,1,12,9,13,7,6
CAIS DO PORTO,0,0,0,0,0,1,0,0,0,2,0,0
CAJAZEIRAS,0,2,0,0,0,1,3,1,1,3,1,1
CAMBEBA,1,3,2,2,1,1,4,3,1,2,2,0
CANINDEZINHO,2,1,5,7,5,3,6,3,6,14,5,3
CARLITO PAMPLONA,4,0,1,4,2,1,4,5,4,7,5,2
CASTELAO,5,0,2,1,0,2,2,3,1,2,7,2
CENTRO,11,2,9,5,6,6,16,16,19,17,15,11
CIDADE 2000,1,0,1,2,0,0,1,2,4,3,0,2
CIDADE DOS FUNCIONARIOS,7,3,3,9,1,10,3,6,10,7,6,6
COACU,0,0,0,0,0,0,0,0,0,0,0,0
COCO,4,1,0,1,3,1,2,0,3,3,2,3
CONJUNTO CEARA I,3,1,2,2,1,3,3,3,3,5,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...
PARQUE SAO JOSE,3,4,5,8,5,9,3,7,1,8,8,5
PARQUELANDIA,10,5,14,9,15,22,16,8,12,13,16,24
PARREAO,1,0,0,0,2,1,0,0,1,0,0,0
PASSARE,2,1,4,2,1,2,3,3,9,3,9,3
PAUPINA,1,0,0,0,1,0,2,1,1,3,0,1
PEDRAS,1,1,2,0,1,3,2,4,0,4,0,0
PICI,6,2,4,6,6,2,4,7,7,0,6,6
PIRAMBU,6,1,2,0,2,2,5,0,1,1,1,3
PLANALTO AYRTON SENNA,1,0,0,0,0,1,1,0,1,5,2,2
PRAIA DE IRACEMA,3,1,4,2,2,2,2,3,1,1,0,2
PRAIA DO FUTURO I,0,2,0,2,0,1,1,2,2,2,0,3
PRAIA DO FUTURO II,0,1,1,2,0,2,0,2,2,2,0,2
PREFEITO JOSE VALTER,10,6,5,3,6,7,3,5,9,15,14,9
PRESIDENTE KENNEDY,9,1,2,1,3,3,2,1,4,7,3,8
QUINTINO CUNHA,4,1,2,4,7,5,7,4,5,5,3,7
RODOLFO TEOFILO,2,1,4,1,5,5,1,5,2,2,7,6
SABIAGUABA,0,0,1,0,0,0,0,0,2,1,0,2
SALINAS,0,0,0,1,0,0,0,0,0,0,0,1
SAO BENTO,0,0,0,0,0,0,0,0,0,0,0,0
SAO GERARDO,7,4,0,2,4,5,3,3,4,7,8,2
SAO JOAO DO TAUAPE,7,2,2,2,5,7,3,2,5,4,11,3
SAPIRANGA COITE,2,1,1,1,1,2,0,2,2,4,2,1
SERRINHA,6,1,2,2,1,3,1,3,0,7,9,2
SIQUEIRA,12,2,4,15,9,10,6,17,4,11,16,9
VARJOTA,5,1,3,1,2,0,1,2,1,1,0,0
VICENTE PINZON,1,0,3,0,1,1,1,0,0,2,2,0
MANOEL SATIRO,3,5,2,10,6,3,5,3,7,8,7,7
VILA PERY,5,4,4,8,12,8,6,7,5,7,5,17
VILA UNIAO,2,1,1,0,2,2,4,6,4,6,2,2
VILA VELHA,4,2,6,1,3,2,5,3,3,4,3,5

In [119]:
df = homicidios
#df['2012-01-01 '].append(df['Column 2']).reset_index(drop=True)
df = df['2012-01-01'].append(df['2012-02-01']).append(df['2012-03-01']).append(df['2012-04-01']).append(df['2012-05-01']).append(df['2012-06-01']).append(df['2012-07-01']).append(df['2012-08-01']).append(df['2012-09-01']).append(df['2012-10-01']).append(df['2012-11-01']).append(df['2012-12-01']).reset_index()
df = df.rename(columns={0: "Homicidios"})
df

                       Bairro  Homicidios
0                  AEROLANDIA           3
1                   AEROPORTO           0
2             JOSE DE ALENCAR           4
3                     ALDEOTA           1
4             ALTO DA BALANCA           1
5                ALVARO WEYNE           4
6              AMADEU FURTADO           0
7                      ANCURI           3
8             ANTONIO BEZERRA           2
9                AUTRAN NUNES           3
10                 DE LOURDES           0
11             BARRA DO CEARA           5
12                    BARROSO           5
13                 BELA VISTA           0
14                    BENFICA           0
15                 BOM FUTURO           0
16                 BOM JARDIM           4
17                 BONSUCESSO           3
18              CAIS DO PORTO           5
19                 CAJAZEIRAS           1
20                    CAMBEBA           0
21               CANINDEZINHO           2
22           CARLITO PAMPLONA           4
23                   CASTELAO           1
24                     CENTRO           1
25                CIDADE 2000           1
26    CIDADE DOS FUNCIONARIOS           1
27                      COACU           0
28                       COCO           1
29           CONJUNTO CEARA I           1
...                       ...         ...
1398          PARQUE SAO JOSE           3
1399             PARQUELANDIA           0
1400                  PARREAO           0
1401                  PASSARE           8
1402                  PAUPINA           0
1403                   PEDRAS           0
1404                     PICI           1
1405                  PIRAMBU           2
1406    PLANALTO AYRTON SENNA           1
1407         PRAIA DE IRACEMA           0
1408        PRAIA DO FUTURO I           0
1409       PRAIA DO FUTURO II           0
1410     PREFEITO JOSE VALTER           2
1411       PRESIDENTE KENNEDY           1
1412           QUINTINO CUNHA           1
1413          RODOLFO TEOFILO           0
1414               SABIAGUABA           3
1415                  SALINAS           0
1416                SAO BENTO           0
1417              SAO GERARDO           0
1418       SAO JOAO DO TAUAPE           1
1419          SAPIRANGA COITE           3
1420                 SERRINHA           2
1421                 SIQUEIRA           0
1422                  VARJOTA           0
1423           VICENTE PINZON           2
1424            MANOEL SATIRO           0
1425                VILA PERY           0
1426               VILA UNIAO           0
1427               VILA VELHA           5

[1428 rows x 2 columns]

In [120]:
months_dict = {1:'2012-01-01',
               2:'2012-02-01',
               3:'2012-03-01',
               4:'2012-04-01',
               5:'2012-05-01',
               6:'2012-06-01',
               7:'2012-07-01',
               8:'2012-08-01',
               9:'2012-09-01',
               10:'2012-10-01',
               11:'2012-11-01',
               12:'2012-12-01'}
months_dict

{1: '2012-01-01',
 2: '2012-02-01',
 3: '2012-03-01',
 4: '2012-04-01',
 5: '2012-05-01',
 6: '2012-06-01',
 7: '2012-07-01',
 8: '2012-08-01',
 9: '2012-09-01',
 10: '2012-10-01',
 11: '2012-11-01',
 12: '2012-12-01'}

In [121]:
months = []
key = 0
for i in range (len(roubos)*len(roubos.columns)):    
    if (i%len(roubos) == 0):
        key += 1
        #print('key = ', key, end = ' ')
        #print('i = ',i)
    string = months_dict[key]
    months.append(string)
    
len(months)

1428

In [124]:
df['Mês'] = months
homicidios2 = df[['Bairro','Mês','Homicidios']]
homicidios2

                       Bairro         Mês  Homicidios
0                  AEROLANDIA  2012-01-01           3
1                   AEROPORTO  2012-01-01           0
2             JOSE DE ALENCAR  2012-01-01           4
3                     ALDEOTA  2012-01-01           1
4             ALTO DA BALANCA  2012-01-01           1
5                ALVARO WEYNE  2012-01-01           4
6              AMADEU FURTADO  2012-01-01           0
7                      ANCURI  2012-01-01           3
8             ANTONIO BEZERRA  2012-01-01           2
9                AUTRAN NUNES  2012-01-01           3
10                 DE LOURDES  2012-01-01           0
11             BARRA DO CEARA  2012-01-01           5
12                    BARROSO  2012-01-01           5
13                 BELA VISTA  2012-01-01           0
14                    BENFICA  2012-01-01           0
15                 BOM FUTURO  2012-01-01           0
16                 BOM JARDIM  2012-01-01           4
17                 BONSUCESSO  2012-01-01           3
18              CAIS DO PORTO  2012-01-01           5
19                 CAJAZEIRAS  2012-01-01           1
20                    CAMBEBA  2012-01-01           0
21               CANINDEZINHO  2012-01-01           2
22           CARLITO PAMPLONA  2012-01-01           4
23                   CASTELAO  2012-01-01           1
24                     CENTRO  2012-01-01           1
25                CIDADE 2000  2012-01-01           1
26    CIDADE DOS FUNCIONARIOS  2012-01-01           1
27                      COACU  2012-01-01           0
28                       COCO  2012-01-01           1
29           CONJUNTO CEARA I  2012-01-01           1
...                       ...         ...         ...
1398          PARQUE SAO JOSE  2012-12-01           3
1399             PARQUELANDIA  2012-12-01           0
1400                  PARREAO  2012-12-01           0
1401                  PASSARE  2012-12-01           8
1402                  PAUPINA  2012-12-01           0
1403                   PEDRAS  2012-12-01           0
1404                     PICI  2012-12-01           1
1405                  PIRAMBU  2012-12-01           2
1406    PLANALTO AYRTON SENNA  2012-12-01           1
1407         PRAIA DE IRACEMA  2012-12-01           0
1408        PRAIA DO FUTURO I  2012-12-01           0
1409       PRAIA DO FUTURO II  2012-12-01           0
1410     PREFEITO JOSE VALTER  2012-12-01           2
1411       PRESIDENTE KENNEDY  2012-12-01           1
1412           QUINTINO CUNHA  2012-12-01           1
1413          RODOLFO TEOFILO  2012-12-01           0
1414               SABIAGUABA  2012-12-01           3
1415                  SALINAS  2012-12-01           0
1416                SAO BENTO  2012-12-01           0
1417              SAO GERARDO  2012-12-01           0
1418       SAO JOAO DO TAUAPE  2012-12-01           1
1419          SAPIRANGA COITE  2012-12-01           3
1420                 SERRINHA  2012-12-01           2
1421                 SIQUEIRA  2012-12-01           0
1422                  VARJOTA  2012-12-01           0
1423           VICENTE PINZON  2012-12-01           2
1424            MANOEL SATIRO  2012-12-01           0
1425                VILA PERY  2012-12-01           0
1426               VILA UNIAO  2012-12-01           0
1427               VILA VELHA  2012-12-01           5

[1428 rows x 3 columns]

In [125]:
df = roubos
#df['2012-01-01 '].append(df['Column 2']).reset_index(drop=True)
df = df['2012-01-01'].append(df['2012-02-01']).append(df['2012-03-01']).append(df['2012-04-01']).append(df['2012-05-01']).append(df['2012-06-01']).append(df['2012-07-01']).append(df['2012-08-01']).append(df['2012-09-01']).append(df['2012-10-01']).append(df['2012-11-01']).append(df['2012-12-01']).reset_index()
df = df.rename(columns={0: "Roubos"})
df

                       Bairro  Roubos
0                  AEROLANDIA       4
1                   AEROPORTO       0
2             JOSE DE ALENCAR       0
3                     ALDEOTA      19
4             ALTO DA BALANCA       0
5                ALVARO WEYNE       3
6              AMADEU FURTADO       0
7                      ANCURI       0
8             ANTONIO BEZERRA      14
9                AUTRAN NUNES       2
10                 DE LOURDES       0
11             BARRA DO CEARA       9
12                    BARROSO       6
13                 BELA VISTA      11
14                    BENFICA       6
15                 BOM FUTURO       0
16                 BOM JARDIM      12
17                 BONSUCESSO       7
18              CAIS DO PORTO       0
19                 CAJAZEIRAS       0
20                    CAMBEBA       1
21               CANINDEZINHO       2
22           CARLITO PAMPLONA       4
23                   CASTELAO       5
24                     CENTRO      11
25                CIDADE 2000       1
26    CIDADE DOS FUNCIONARIOS       7
27                      COACU       0
28                       COCO       4
29           CONJUNTO CEARA I       3
...                       ...     ...
1398          PARQUE SAO JOSE       5
1399             PARQUELANDIA      24
1400                  PARREAO       0
1401                  PASSARE       3
1402                  PAUPINA       1
1403                   PEDRAS       0
1404                     PICI       6
1405                  PIRAMBU       3
1406    PLANALTO AYRTON SENNA       2
1407         PRAIA DE IRACEMA       2
1408        PRAIA DO FUTURO I       3
1409       PRAIA DO FUTURO II       2
1410     PREFEITO JOSE VALTER       9
1411       PRESIDENTE KENNEDY       8
1412           QUINTINO CUNHA       7
1413          RODOLFO TEOFILO       6
1414               SABIAGUABA       2
1415                  SALINAS       1
1416                SAO BENTO       0
1417              SAO GERARDO       2
1418       SAO JOAO DO TAUAPE       3
1419          SAPIRANGA COITE       1
1420                 SERRINHA       2
1421                 SIQUEIRA       9
1422                  VARJOTA       0
1423           VICENTE PINZON       0
1424            MANOEL SATIRO       7
1425                VILA PERY      17
1426               VILA UNIAO       2
1427               VILA VELHA       5

[1428 rows x 2 columns]

In [127]:
df['Mês'] = months
roubos2 = df[['Bairro','Mês','Roubos']]
roubos2

                       Bairro         Mês  Roubos
0                  AEROLANDIA  2012-01-01       4
1                   AEROPORTO  2012-01-01       0
2             JOSE DE ALENCAR  2012-01-01       0
3                     ALDEOTA  2012-01-01      19
4             ALTO DA BALANCA  2012-01-01       0
5                ALVARO WEYNE  2012-01-01       3
6              AMADEU FURTADO  2012-01-01       0
7                      ANCURI  2012-01-01       0
8             ANTONIO BEZERRA  2012-01-01      14
9                AUTRAN NUNES  2012-01-01       2
10                 DE LOURDES  2012-01-01       0
11             BARRA DO CEARA  2012-01-01       9
12                    BARROSO  2012-01-01       6
13                 BELA VISTA  2012-01-01      11
14                    BENFICA  2012-01-01       6
15                 BOM FUTURO  2012-01-01       0
16                 BOM JARDIM  2012-01-01      12
17                 BONSUCESSO  2012-01-01       7
18              CAIS DO PORTO  2012-01-01       0
19                 CAJAZEIRAS  2012-01-01       0
20                    CAMBEBA  2012-01-01       1
21               CANINDEZINHO  2012-01-01       2
22           CARLITO PAMPLONA  2012-01-01       4
23                   CASTELAO  2012-01-01       5
24                     CENTRO  2012-01-01      11
25                CIDADE 2000  2012-01-01       1
26    CIDADE DOS FUNCIONARIOS  2012-01-01       7
27                      COACU  2012-01-01       0
28                       COCO  2012-01-01       4
29           CONJUNTO CEARA I  2012-01-01       3
...                       ...         ...     ...
1398          PARQUE SAO JOSE  2012-12-01       5
1399             PARQUELANDIA  2012-12-01      24
1400                  PARREAO  2012-12-01       0
1401                  PASSARE  2012-12-01       3
1402                  PAUPINA  2012-12-01       1
1403                   PEDRAS  2012-12-01       0
1404                     PICI  2012-12-01       6
1405                  PIRAMBU  2012-12-01       3
1406    PLANALTO AYRTON SENNA  2012-12-01       2
1407         PRAIA DE IRACEMA  2012-12-01       2
1408        PRAIA DO FUTURO I  2012-12-01       3
1409       PRAIA DO FUTURO II  2012-12-01       2
1410     PREFEITO JOSE VALTER  2012-12-01       9
1411       PRESIDENTE KENNEDY  2012-12-01       8
1412           QUINTINO CUNHA  2012-12-01       7
1413          RODOLFO TEOFILO  2012-12-01       6
1414               SABIAGUABA  2012-12-01       2
1415                  SALINAS  2012-12-01       1
1416                SAO BENTO  2012-12-01       0
1417              SAO GERARDO  2012-12-01       2
1418       SAO JOAO DO TAUAPE  2012-12-01       3
1419          SAPIRANGA COITE  2012-12-01       1
1420                 SERRINHA  2012-12-01       2
1421                 SIQUEIRA  2012-12-01       9
1422                  VARJOTA  2012-12-01       0
1423           VICENTE PINZON  2012-12-01       0
1424            MANOEL SATIRO  2012-12-01       7
1425                VILA PERY  2012-12-01      17
1426               VILA UNIAO  2012-12-01       2
1427               VILA VELHA  2012-12-01       5

[1428 rows x 3 columns]

In [129]:
df = pd.merge(homicidios2,roubos2,on=['Mês','Bairro'])
df

                       Bairro         Mês  Homicidios  Roubos
0                  AEROLANDIA  2012-01-01           3       4
1                   AEROPORTO  2012-01-01           0       0
2             JOSE DE ALENCAR  2012-01-01           4       0
3                     ALDEOTA  2012-01-01           1      19
4             ALTO DA BALANCA  2012-01-01           1       0
5                ALVARO WEYNE  2012-01-01           4       3
6              AMADEU FURTADO  2012-01-01           0       0
7                      ANCURI  2012-01-01           3       0
8             ANTONIO BEZERRA  2012-01-01           2      14
9                AUTRAN NUNES  2012-01-01           3       2
10                 DE LOURDES  2012-01-01           0       0
11             BARRA DO CEARA  2012-01-01           5       9
12                    BARROSO  2012-01-01           5       6
13                 BELA VISTA  2012-01-01           0      11
14                    BENFICA  2012-01-01           0       6
15                 BOM FUTURO  2012-01-01           0       0
16                 BOM JARDIM  2012-01-01           4      12
17                 BONSUCESSO  2012-01-01           3       7
18              CAIS DO PORTO  2012-01-01           5       0
19                 CAJAZEIRAS  2012-01-01           1       0
20                    CAMBEBA  2012-01-01           0       1
21               CANINDEZINHO  2012-01-01           2       2
22           CARLITO PAMPLONA  2012-01-01           4       4
23                   CASTELAO  2012-01-01           1       5
24                     CENTRO  2012-01-01           1      11
25                CIDADE 2000  2012-01-01           1       1
26    CIDADE DOS FUNCIONARIOS  2012-01-01           1       7
27                      COACU  2012-01-01           0       0
28                       COCO  2012-01-01           1       4
29           CONJUNTO CEARA I  2012-01-01           1       3
...                       ...         ...         ...     ...
1398          PARQUE SAO JOSE  2012-12-01           3       5
1399             PARQUELANDIA  2012-12-01           0      24
1400                  PARREAO  2012-12-01           0       0
1401                  PASSARE  2012-12-01           8       3
1402                  PAUPINA  2012-12-01           0       1
1403                   PEDRAS  2012-12-01           0       0
1404                     PICI  2012-12-01           1       6
1405                  PIRAMBU  2012-12-01           2       3
1406    PLANALTO AYRTON SENNA  2012-12-01           1       2
1407         PRAIA DE IRACEMA  2012-12-01           0       2
1408        PRAIA DO FUTURO I  2012-12-01           0       3
1409       PRAIA DO FUTURO II  2012-12-01           0       2
1410     PREFEITO JOSE VALTER  2012-12-01           2       9
1411       PRESIDENTE KENNEDY  2012-12-01           1       8
1412           QUINTINO CUNHA  2012-12-01           1       7
1413          RODOLFO TEOFILO  2012-12-01           0       6
1414               SABIAGUABA  2012-12-01           3       2
1415                  SALINAS  2012-12-01           0       1
1416                SAO BENTO  2012-12-01           0       0
1417              SAO GERARDO  2012-12-01           0       2
1418       SAO JOAO DO TAUAPE  2012-12-01           1       3
1419          SAPIRANGA COITE  2012-12-01           3       1
1420                 SERRINHA  2012-12-01           2       2
1421                 SIQUEIRA  2012-12-01           0       9
1422                  VARJOTA  2012-12-01           0       0
1423           VICENTE PINZON  2012-12-01           2       0
1424            MANOEL SATIRO  2012-12-01           0       7
1425                VILA PERY  2012-12-01           0      17
1426               VILA UNIAO  2012-12-01           0       2
1427               VILA VELHA  2012-12-01           5       5

[1428 rows x 4 columns]

In [130]:
df.to_excel("Fortaleza_Roubos_Homicidios_2012.xlsx")